Add UrlDataFile
bricolages/redshift_connector pull request #1
Opened 2017-03-14 05:43 UTC by KOBA789

- S3 の presigned url を S3DataFile から取得できるようにしました
- presigned url などの URL から生成できる DataFile として UrlDataFile を実装しました
  - またその bundle として UrlDataFileBundle を実装しました
  - これらに伴って DataFileBase / DataFileBundleBase という抽象クラスを追加しています

2017-03-16 07:20 UTC, KOBA789 commented
@aamine レビューお願いします :bow:

2017-03-16 07:57 UTC, aamine commented on lib/redshift-connector/s3_data_file_bundle.rb
> -        .select {|obj| obj.data_object? }
これなくなって大丈夫なの？

2017-03-16 07:59 UTC, aamine commented on lib/redshift-connector/data_file_base.rb
> +  class DataFileBase
Baseという名前が大嫌いなので単に `DataFile` か、せめて `AbstractDataFile` とかでなんとか……

2017-03-16 07:59 UTC, aamine commented on lib/redshift-connector/data_file_base.rb
> +  class DataFileBase
Baseという名前が大嫌いなので単に `DataFile` か、せめて `AbstractDataFile` とかでなんとか……

2017-03-16 08:00 UTC, KOBA789 commented on lib/redshift-connector/data_file_base.rb
> +  class DataFileBase
他に Reader の方で Abstract 使ってるので Abstract に揃えます

2017-03-16 08:02 UTC, KOBA789 commented on lib/redshift-connector/s3_data_file_bundle.rb
> -        .select {|obj| obj.data_object? }
こっちに移した(メソッド自体も改名してる)ので大丈夫です https://github.com/aamine/redshift-connector/pull/1/files#diff-72f0c738c33ad11737f0d2239a23b79bR19

2017-03-22 07:11 UTC, aamine requested changes
fix them

2017-03-22 07:11 UTC, aamine commented on lib/redshift-connector/s3_data_file.rb
> +  class S3DataFile < DataFileBase
スーパークラス名が変わってない

2017-03-22 07:11 UTC, aamine commented on lib/redshift-connector/url_data_file.rb
> +  class UrlDataFile < DataFileBase
スーパークラス名

2017-03-22 07:11 UTC, aamine commented on lib/redshift-connector/url_data_file_bundle.rb
> +  class UrlDataFileBundle < DataFileBundleBase
スーパークラス名

2017-03-22 07:11 UTC, aamine commented on lib/redshift-connector/s3_data_file_bundle.rb
> +  class S3DataFileBundle < DataFileBundleBase
スーパークラス名

2017-03-22 07:13 UTC, aamine commented
ping @KOBA789

2017-03-22 07:13 UTC, KOBA789 commented
スーパークラス名壊れてるの気づいて直したのに push するの忘れてました

2017-03-22 07:16 UTC, aamine approved these changes
LGTM

2017-03-22 07:16 UTC, merged